<?php

/**
 * @file
 * Contains ed_password_policy.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function ed_password_policy_form_legal_login_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Adding custom modifications for the login page.
  unset($form['legal']['conditions']['#title']);
  $form['legal']['legal_accept']['#title'] = 'Acknowledge warning';
  $form['legal']['#title'] = 'Acknowledge warning';
  $form['#title'] = 'Warning';
}
