# Schema for configuration files of the Password Policy Name submodule.

password_policy.constraint.plugin.password_name:
  type: password_policy.constraint.plugin
  mapping:
    disallow_name:
      type: boolean
      label: 'Disallow name'
