# Schema for configuration files of the Password Policy Password submodule.

password_policy.constraint.plugin.password_password:
  type: password_policy.constraint.plugin
  mapping:
    disallow_password:
      type: boolean
      label: 'Disallow password'
