# Schema for configuration files of the Password Policy Systemname submodule.

password_policy.constraint.plugin.password_systemname:
  type: password_policy.constraint.plugin
  mapping:
    disallow_systemname:
      type: boolean
      label: 'Disallow systemname'
